unbind C-b
set-option -g prefix C-s

set-option -g status-style bg=cyan
set -g mode-keys vi
set -g status-keys vi
set-window-option -g mode-keys vi

# Copy key bindings keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Split pane on CWD
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# TMUX ergonomics
set -g detach-on-destroy off # don't exit from tmux when closing a session
set -g status-justify left
